//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_42
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// РаспПрих.
    /// </summary>
    // *** Start programmer edit section *** (РаспПрих CustomAttributes)

    // *** End programmer edit section *** (РаспПрих CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РаспПрихE", new string[] {
            "Урок as \'Урок\'",
            "ПериодНачала as \'Период Начала\'",
            "ПериодКонца as \'Период Окончания\'"})]
    [View("РаспПрихL", new string[] {
            "Урок as \'Урок\'",
            "ПериодНачала as \'Период Начала\'",
            "ПериодКонца as \'Период Окончания\'"})]
    public class РаспПрих : ICSSoft.STORMNET.DataObject
    {
        
        private string fУрок;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fПериодНачала;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fПериодКонца;
        
        // *** Start programmer edit section *** (РаспПрих CustomMembers)

        // *** End programmer edit section *** (РаспПрих CustomMembers)

        
        /// <summary>
        /// ПериодКонца.
        /// </summary>
        // *** Start programmer edit section *** (РаспПрих.ПериодКонца CustomAttributes)

        // *** End programmer edit section *** (РаспПрих.ПериодКонца CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ПериодКонца
        {
            get
            {
                // *** Start programmer edit section *** (РаспПрих.ПериодКонца Get start)

                // *** End programmer edit section *** (РаспПрих.ПериодКонца Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fПериодКонца;
                // *** Start programmer edit section *** (РаспПрих.ПериодКонца Get end)

                // *** End programmer edit section *** (РаспПрих.ПериодКонца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспПрих.ПериодКонца Set start)

                // *** End programmer edit section *** (РаспПрих.ПериодКонца Set start)
                this.fПериодКонца = value;
                // *** Start programmer edit section *** (РаспПрих.ПериодКонца Set end)

                // *** End programmer edit section *** (РаспПрих.ПериодКонца Set end)
            }
        }
        
        /// <summary>
        /// ПериодНачала.
        /// </summary>
        // *** Start programmer edit section *** (РаспПрих.ПериодНачала CustomAttributes)

        // *** End programmer edit section *** (РаспПрих.ПериодНачала CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ПериодНачала
        {
            get
            {
                // *** Start programmer edit section *** (РаспПрих.ПериодНачала Get start)

                // *** End programmer edit section *** (РаспПрих.ПериодНачала Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fПериодНачала;
                // *** Start programmer edit section *** (РаспПрих.ПериодНачала Get end)

                // *** End programmer edit section *** (РаспПрих.ПериодНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспПрих.ПериодНачала Set start)

                // *** End programmer edit section *** (РаспПрих.ПериодНачала Set start)
                this.fПериодНачала = value;
                // *** Start programmer edit section *** (РаспПрих.ПериодНачала Set end)

                // *** End programmer edit section *** (РаспПрих.ПериодНачала Set end)
            }
        }
        
        /// <summary>
        /// Урок.
        /// </summary>
        // *** Start programmer edit section *** (РаспПрих.Урок CustomAttributes)

        // *** End programmer edit section *** (РаспПрих.Урок CustomAttributes)
        [StrLen(255)]
        public virtual string Урок
        {
            get
            {
                // *** Start programmer edit section *** (РаспПрих.Урок Get start)

                // *** End programmer edit section *** (РаспПрих.Урок Get start)
                string result = this.fУрок;
                // *** Start programmer edit section *** (РаспПрих.Урок Get end)

                // *** End programmer edit section *** (РаспПрих.Урок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспПрих.Урок Set start)

                // *** End programmer edit section *** (РаспПрих.Урок Set start)
                this.fУрок = value;
                // *** Start programmer edit section *** (РаспПрих.Урок Set end)

                // *** End programmer edit section *** (РаспПрих.Урок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РаспПрихE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаспПрихE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаспПрихE", typeof(IIS.Prilozhenie_42.РаспПрих));
                }
            }
            
            /// <summary>
            /// "РаспПрихL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаспПрихL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаспПрихL", typeof(IIS.Prilozhenie_42.РаспПрих));
                }
            }
        }
    }
}
