//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_42
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справ уч.
    /// </summary>
    // *** Start programmer edit section *** (СправУч CustomAttributes)

    // *** End programmer edit section *** (СправУч CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник Учеников")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправУчE", new string[] {
            "Фио as \'Фио\'"})]
    [View("СправУчL", new string[] {
            "Фио as \'Фио\'"})]
    public class СправУч : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        // *** Start programmer edit section *** (СправУч CustomMembers)

        // *** End programmer edit section *** (СправУч CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СправУч.Фио CustomAttributes)

        // *** End programmer edit section *** (СправУч.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СправУч.Фио Get start)

                // *** End programmer edit section *** (СправУч.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СправУч.Фио Get end)

                // *** End programmer edit section *** (СправУч.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУч.Фио Set start)

                // *** End programmer edit section *** (СправУч.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СправУч.Фио Set end)

                // *** End programmer edit section *** (СправУч.Фио Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправУчE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУчE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУчE", typeof(IIS.Prilozhenie_42.СправУч));
                }
            }
            
            /// <summary>
            /// "СправУчL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУчL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУчL", typeof(IIS.Prilozhenie_42.СправУч));
                }
            }
        }
    }
}
